#cloud-config
package_update: true
packages:
  - sudo

users:
  - name: scsadmin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id: None
    ssh_authorized_keys:
      - <your-public-ssh-key>

runcmd:  
  - echo "Port 2222" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - cp /home/ubuntu/.ssh/authorized_keys /home/scsadmin/.ssh/
  - chown -R scsadmin:scsadmin /home/scsadmin/.ssh
  - chmod 700 /home/scsadmin/.ssh
  - chmod 600 /home/scsadmin/.ssh/authorized_keys
  - sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/#PasswordAuthentication no/PasswordAuthentication no/' /etc/ssh/sshd_config
  - |
    PRIVATE_IP=$(hostname -I | awk '{print $1}')
    PRIVATE_IP_DASHED=$(echo $PRIVATE_IP | tr '.' '-')
    NEW_HOSTNAME="scs-bastion-$PRIVATE_IP_DASHED"
    hostnamectl set-hostname $NEW_HOSTNAME
    echo "127.0.0.1 $NEW_HOSTNAME" >> /etc/hosts
  - systemctl restart sshd